// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lipibykkywbcbsiyywet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcGlieWtreXdiY2JzaXl5d2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNDkwMTcsImV4cCI6MjA3NDkyNTAxN30.RBMkBAOHWEjPf79Hx6DCZsWcOkZsaCYjI24joors-7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});